name: minh_demo_bloc
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  http: ^0.13.0
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mocktail: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - images/image1.jpg
    - images/image2.jpg
    - images/image3.jpg
    - images/image4.jpg
    - images/image5.jpg
    - images/image6.jpg
    - images/image7.jpg
    - images/image8.jpg
    - images/image9.jpg
    - images/image10.jpg
